name: simple_chess_clock
description: A simple chess clock app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^2.0.0
  equatable: ^1.0.0 

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/simplechessclock.png"

flutter:
  uses-material-design: true